/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package components;

/**
 *
 * @author dpaiv
 */
public class AplicarMedicamento extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AplicarMedicamento.class.getName());

    /**
     * Creates new form MenuMedico
     */
    public AplicarMedicamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDrMenu = new javax.swing.JLabel();
        textFuncMenuDr = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textFuncMenuDr1 = new javax.swing.JLabel();
        textFuncMenuDr2 = new javax.swing.JLabel();
        cpfAplicarMedicamento = new javax.swing.JTextField();
        nomeAplicarMedicamento = new javax.swing.JTextField();
        idPacienteAplicarMedicamento = new javax.swing.JTextField();
        textFuncMenuDr5 = new javax.swing.JLabel();
        idAplicarMedicamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtDrMenu.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        txtDrMenu.setText("Aplicar Medicamento");
        txtDrMenu.setToolTipText("");

        textFuncMenuDr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textFuncMenuDr.setText("Nome do paciente");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Aplicar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        textFuncMenuDr1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textFuncMenuDr1.setText("ID paciente");

        textFuncMenuDr2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textFuncMenuDr2.setText("CPF paciente");

        cpfAplicarMedicamento.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cpfAplicarMedicamento.addActionListener(this::cpfAplicarMedicamentoActionPerformed);

        nomeAplicarMedicamento.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        idPacienteAplicarMedicamento.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        textFuncMenuDr5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textFuncMenuDr5.setText("ID Receita");

        idAplicarMedicamento.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        idAplicarMedicamento.addActionListener(this::idAplicarMedicamentoActionPerformed);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel1.setText("Clique em aplicar para confirmar os medicamentos que serão aplicados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFuncMenuDr2)
                        .addGap(18, 18, 18)
                        .addComponent(cpfAplicarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDrMenu)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFuncMenuDr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomeAplicarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFuncMenuDr1)
                        .addGap(18, 18, 18)
                        .addComponent(idPacienteAplicarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFuncMenuDr5)
                        .addGap(18, 18, 18)
                        .addComponent(idAplicarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 275, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(txtDrMenu)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFuncMenuDr5)
                            .addComponent(idAplicarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFuncMenuDr2)
                            .addComponent(cpfAplicarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFuncMenuDr)
                            .addComponent(nomeAplicarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFuncMenuDr1)
                            .addComponent(idPacienteAplicarMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        setSize(new java.awt.Dimension(916, 509));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cpfAplicarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfAplicarMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfAplicarMedicamentoActionPerformed

    private void idAplicarMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAplicarMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAplicarMedicamentoActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AplicarMedicamento dialog = new AplicarMedicamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfAplicarMedicamento;
    private javax.swing.JTextField idAplicarMedicamento;
    private javax.swing.JTextField idPacienteAplicarMedicamento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nomeAplicarMedicamento;
    private javax.swing.JLabel textFuncMenuDr;
    private javax.swing.JLabel textFuncMenuDr1;
    private javax.swing.JLabel textFuncMenuDr2;
    private javax.swing.JLabel textFuncMenuDr5;
    private javax.swing.JLabel txtDrMenu;
    // End of variables declaration//GEN-END:variables
}
