/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package components;

import Conexao.PacienteDAO;
import Conexao.UsuarioDAO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import models.Pacientes.Paciente;

/**
 *
 * @author dpaiv
 */
public class CadastroPaciente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroPaciente.class.getName());
    PacienteDAO pacDao = new PacienteDAO();
    
    /**
     * Creates new form Cadastro
     */
    public CadastroPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textCadastro = new javax.swing.JLabel();
        txtCpfCadastro = new javax.swing.JLabel();
        cpfCadastroPaciente = new javax.swing.JTextField();
        textNomeCadastro = new javax.swing.JLabel();
        nomeCadastroPaciente = new javax.swing.JTextField();
        textSobreNomeCadastro = new javax.swing.JLabel();
        telefoneCadastroPaciente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        textSobreNomeCadastro1 = new javax.swing.JLabel();
        emailCadastroPaciente = new javax.swing.JTextField();
        textSobreNomeCadastro5 = new javax.swing.JLabel();
        dataNascimentoCadastoPaciente = new javax.swing.JTextField();
        textSobreNomeCadastro6 = new javax.swing.JLabel();
        sexoComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO");

        textCadastro.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        textCadastro.setText("CADASTRO PACIENTE");

        txtCpfCadastro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtCpfCadastro.setText("CPF");

        cpfCadastroPaciente.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cpfCadastroPaciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpfCadastroPaciente.setToolTipText("Informe apenas os números do CPF");
        cpfCadastroPaciente.addActionListener(this::cpfCadastroPacienteActionPerformed);

        textNomeCadastro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textNomeCadastro.setText("Nome:");

        nomeCadastroPaciente.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        nomeCadastroPaciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeCadastroPaciente.addActionListener(this::nomeCadastroPacienteActionPerformed);

        textSobreNomeCadastro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro.setText("Telefone");

        telefoneCadastroPaciente.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        textSobreNomeCadastro1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro1.setText("Email");

        emailCadastroPaciente.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N

        textSobreNomeCadastro5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro5.setText("Data Nascimento");

        dataNascimentoCadastoPaciente.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        dataNascimentoCadastoPaciente.addActionListener(this::dataNascimentoCadastoPacienteActionPerformed);

        textSobreNomeCadastro6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro6.setText("Sexo");

        sexoComboBox.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        sexoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", " " }));
        sexoComboBox.addActionListener(this::sexoComboBoxActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textSobreNomeCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(telefoneCadastroPaciente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textNomeCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(nomeCadastroPaciente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCpfCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(cpfCadastroPaciente))
                            .addComponent(textCadastro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textSobreNomeCadastro1)
                                .addGap(18, 18, 18)
                                .addComponent(emailCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textSobreNomeCadastro5)
                                .addGap(18, 18, 18)
                                .addComponent(dataNascimentoCadastoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textSobreNomeCadastro6)
                                .addGap(18, 18, 18)
                                .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(textCadastro)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfCadastro)
                    .addComponent(cpfCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomeCadastro)
                    .addComponent(nomeCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSobreNomeCadastro)
                    .addComponent(telefoneCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSobreNomeCadastro1)
                    .addComponent(emailCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSobreNomeCadastro5)
                    .addComponent(dataNascimentoCadastoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSobreNomeCadastro6)
                    .addComponent(sexoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        setSize(new java.awt.Dimension(916, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCadastroPacienteActionPerformed
        telefoneCadastroPaciente.requestFocusInWindow();
    }//GEN-LAST:event_nomeCadastroPacienteActionPerformed

    private void cpfCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfCadastroPacienteActionPerformed
        nomeCadastroPaciente.requestFocusInWindow();
    }//GEN-LAST:event_cpfCadastroPacienteActionPerformed

    private void dataNascimentoCadastoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataNascimentoCadastoPacienteActionPerformed
        sexoComboBox.requestFocusInWindow();
    }//GEN-LAST:event_dataNascimentoCadastoPacienteActionPerformed

    private void sexoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoComboBoxActionPerformed
        jButton1.requestFocusInWindow();
    }//GEN-LAST:event_sexoComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cadastrarPaciente();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void limparCamposPaciente() {
        cpfCadastroPaciente.setText("");
        nomeCadastroPaciente.setText("");
        telefoneCadastroPaciente.setText("");
        emailCadastroPaciente.setText("");
        dataNascimentoCadastoPaciente.setText("");

        if (sexoComboBox.getItemCount() > 0) {
            sexoComboBox.setSelectedIndex(0);
        }
    }
    
    private void cadastrarPaciente() {
        try {
        String cpf = cpfCadastroPaciente.getText().replaceAll("\\D", "");
        String nome = nomeCadastroPaciente.getText().trim();
        String telefone = telefoneCadastroPaciente.getText().trim();
        String email = emailCadastroPaciente.getText().trim();
        String dataDeNascimentoTexto = dataNascimentoCadastoPaciente.getText().trim();

        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nome é obrigatório.");
            return;
        }

        if (cpf.length() != 11) {
            JOptionPane.showMessageDialog(rootPane, "CPF deve conter 11 dígitos.");
            return;
        }

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Email é obrigatório.");
            return;
        }

        if (dataDeNascimentoTexto.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Data de nascimento é obrigatória.");
            return;
        }

        if (sexoComboBox.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(rootPane, "Selecione o sexo do paciente.");
            return;
        }

        String sexo = sexoComboBox.getSelectedItem().toString();

        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate dataNascimento = LocalDate.parse(dataDeNascimentoTexto, formato);

        Paciente pac = new Paciente();

        pac.setNome(nome);
        pac.setCpf(cpf);
        pac.setDataNascimento(dataNascimento);
        pac.setEmail(email);
        pac.setTelefone(telefone);
        pac.setSexo(sexo);

        Integer idPac = pacDao.salvar(pac);
        pac.setId(idPac);

        JOptionPane.showMessageDialog(rootPane, "Paciente cadastrado com sucesso!");

        limparCamposPaciente();

    } catch (java.time.format.DateTimeParseException e) {
        JOptionPane.showMessageDialog(
            rootPane,
            "Data de nascimento inválida. Use o formato dd/MM/yyyy."
        );

    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Erro: " + e.getMessage());
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CadastroPaciente dialog = new CadastroPaciente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfCadastroPaciente;
    private javax.swing.JTextField dataNascimentoCadastoPaciente;
    private javax.swing.JTextField emailCadastroPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField nomeCadastroPaciente;
    private javax.swing.JComboBox<String> sexoComboBox;
    private javax.swing.JTextField telefoneCadastroPaciente;
    private javax.swing.JLabel textCadastro;
    private javax.swing.JLabel textNomeCadastro;
    private javax.swing.JLabel textSobreNomeCadastro;
    private javax.swing.JLabel textSobreNomeCadastro1;
    private javax.swing.JLabel textSobreNomeCadastro5;
    private javax.swing.JLabel textSobreNomeCadastro6;
    private javax.swing.JLabel txtCpfCadastro;
    // End of variables declaration//GEN-END:variables
}
