/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package components;

import Conexao.EnfermeiroDAO;
import Conexao.FuncionarioDAO;
import Conexao.MedicoDAO;
import Conexao.UsuarioDAO;
import javax.swing.JOptionPane;
import models.Funcionarios.Enfermeiro;
import models.Funcionarios.Funcionario;
import models.Funcionarios.Medico;
import models.Usuario;
import utils.Criptografia;

/**
 *
 * @author dpaiv
 */
public class Cadastro extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadastro.class.getName());

      private FuncionarioDAO funcDAO = new FuncionarioDAO();
      private MedicoDAO medDAO = new MedicoDAO();
      private EnfermeiroDAO enfDAO = new EnfermeiroDAO();
      UsuarioDAO userDao = new UsuarioDAO();
    
     public Cadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        Funcionario func  = new Funcionario();
        cpfCadastroUsu.setText("Atualizar Dados");
        jButton1.setText("Salvar");
     
    }
     
    private void cadastrarUsuario() {
    try {
        String cpf = cpfCadastroUsu.getText().trim();
        String nome = nomeCadastroUsu.getText().trim();
        String telefone = telefoneCadastroUsu.getText().trim();
        String email = emailCadastroUsu.getText().trim();

        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nome é obrigatório.");
            return;
        }

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Email é obrigatório.");
            return;
        }

        if (tipoUsuarioCadastroUsu.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(rootPane, "Selecione o tipo de usuário.");
            return;
        }

        String userType = tipoUsuarioCadastroUsu.getSelectedItem().toString();

        Criptografia crip = new Criptografia();
        char[] tempPassword = "1234".toCharArray();
        String hashedTempPassword = crip.criptografar(tempPassword);

        if (userType.equals("Medico")) {

            String especialidade = especialidadeCadastroUsu.getText().trim();
            String crm = crmCadastroUsu.getText().trim();

            Medico med = new Medico();

            med.setNome(nome);
            med.setCpf(cpf);
            med.setTelefone(telefone);

            Integer medId = funcDAO.salvar(med);
            med.setId(medId);

            med.setCrm(crm);
            med.setEspecialidade(especialidade);

            medDAO.salvar(med);

            Usuario user = new Usuario();

            user.setFuncionarioId(medId);
            user.setPerfil("Medico");
            user.setEmail(email);
            user.setSenhaHash(hashedTempPassword);
            user.setDeveTrocarSenha(true);
            user.setAtivo(true);

            userDao.Cadastrar(user);

            JOptionPane.showMessageDialog(rootPane, "Médico cadastrado com sucesso!");

        } else if (userType.equals("Enfermeiro")) {

            String coren = corenCadastroUsu.getText().trim();

            Enfermeiro enf = new Enfermeiro();

            enf.setNome(nome);
            enf.setCpf(cpf);
            enf.setTelefone(telefone);

            Integer enfId = funcDAO.salvar(enf);
            enf.setId(enfId);

            enf.setCoren(coren);

            enfDAO.salvar(enf);

            Usuario user = new Usuario();

            user.setFuncionarioId(enfId);
            user.setPerfil("Enfermeiro");
            user.setEmail(email);
            user.setSenhaHash(hashedTempPassword);
            user.setDeveTrocarSenha(true);
            user.setAtivo(true);

            userDao.Cadastrar(user);

            JOptionPane.showMessageDialog(rootPane, "Enfermeiro cadastrado com sucesso!");

        } else {
            JOptionPane.showMessageDialog(rootPane, "Tipo de usuário inválido.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Erro: " + e.getMessage());
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textCadastro = new javax.swing.JLabel();
        textTipoUsuarioCadastro = new javax.swing.JLabel();
        txtCpfCadastro = new javax.swing.JLabel();
        cpfCadastroUsu = new javax.swing.JTextField();
        tipoUsuarioCadastroUsu = new javax.swing.JComboBox<>();
        textNomeCadastro = new javax.swing.JLabel();
        nomeCadastroUsu = new javax.swing.JTextField();
        textSobreNomeCadastro = new javax.swing.JLabel();
        telefoneCadastroUsu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        textSobreNomeCadastro1 = new javax.swing.JLabel();
        emailCadastroUsu = new javax.swing.JTextField();
        textSobreNomeCadastro2 = new javax.swing.JLabel();
        textSobreNomeCadastro3 = new javax.swing.JLabel();
        crmCadastroUsu = new javax.swing.JTextField();
        corenCadastroUsu = new javax.swing.JTextField();
        textSobreNomeCadastro4 = new javax.swing.JLabel();
        especialidadeCadastroUsu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO");

        textCadastro.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        textCadastro.setText("CADASTRO");

        textTipoUsuarioCadastro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textTipoUsuarioCadastro.setText("Tipo de usuário");

        txtCpfCadastro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtCpfCadastro.setText("CPF");

        cpfCadastroUsu.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cpfCadastroUsu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpfCadastroUsu.setText("Sem Pontos");
        cpfCadastroUsu.addActionListener(this::cpfCadastroUsuActionPerformed);
        cpfCadastroUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpfCadastroUsuKeyPressed(evt);
            }
        });

        tipoUsuarioCadastroUsu.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        tipoUsuarioCadastroUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medico", "Enfermeiro" }));
        tipoUsuarioCadastroUsu.addActionListener(this::tipoUsuarioCadastroUsuActionPerformed);
        tipoUsuarioCadastroUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tipoUsuarioCadastroUsuKeyPressed(evt);
            }
        });

        textNomeCadastro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textNomeCadastro.setText("Nome:");

        nomeCadastroUsu.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        nomeCadastroUsu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeCadastroUsu.addActionListener(this::nomeCadastroUsuActionPerformed);
        nomeCadastroUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nomeCadastroUsuKeyPressed(evt);
            }
        });

        textSobreNomeCadastro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro.setText("Telefone");

        telefoneCadastroUsu.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        telefoneCadastroUsu.addActionListener(this::telefoneCadastroUsuActionPerformed);
        telefoneCadastroUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telefoneCadastroUsuKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Cadastrar");
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        textSobreNomeCadastro1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro1.setText("Email");

        emailCadastroUsu.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        emailCadastroUsu.addActionListener(this::emailCadastroUsuActionPerformed);
        emailCadastroUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailCadastroUsuKeyPressed(evt);
            }
        });

        textSobreNomeCadastro2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro2.setText("CRM");

        textSobreNomeCadastro3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro3.setText("Coren");

        crmCadastroUsu.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        crmCadastroUsu.setText("APENAS PARA MÉDICOS");
        crmCadastroUsu.addActionListener(this::crmCadastroUsuActionPerformed);
        crmCadastroUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                crmCadastroUsuKeyPressed(evt);
            }
        });

        corenCadastroUsu.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        corenCadastroUsu.setText("APENAS PARA ENFERMEIROS");
        corenCadastroUsu.addActionListener(this::corenCadastroUsuActionPerformed);
        corenCadastroUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                corenCadastroUsuKeyPressed(evt);
            }
        });

        textSobreNomeCadastro4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro4.setText("Especialidade");

        especialidadeCadastroUsu.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        especialidadeCadastroUsu.setText("APENAS PARA MÉDICOS");
        especialidadeCadastroUsu.addActionListener(this::especialidadeCadastroUsuActionPerformed);
        especialidadeCadastroUsu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                especialidadeCadastroUsuKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textSobreNomeCadastro4)
                        .addGap(18, 18, 18)
                        .addComponent(especialidadeCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textSobreNomeCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(telefoneCadastroUsu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textNomeCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(nomeCadastroUsu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCpfCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(cpfCadastroUsu))
                            .addComponent(textCadastro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textTipoUsuarioCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoUsuarioCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textSobreNomeCadastro1)
                                .addGap(18, 18, 18)
                                .addComponent(emailCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textSobreNomeCadastro2)
                                .addGap(18, 18, 18)
                                .addComponent(crmCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textSobreNomeCadastro3)
                                .addGap(18, 18, 18)
                                .addComponent(corenCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(textCadastro)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTipoUsuarioCadastro)
                    .addComponent(tipoUsuarioCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfCadastro)
                    .addComponent(cpfCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomeCadastro)
                    .addComponent(nomeCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSobreNomeCadastro)
                    .addComponent(telefoneCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSobreNomeCadastro1)
                    .addComponent(emailCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSobreNomeCadastro4)
                    .addComponent(especialidadeCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSobreNomeCadastro2)
                    .addComponent(crmCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textSobreNomeCadastro3)
                            .addComponent(corenCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        setSize(new java.awt.Dimension(916, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCadastroUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCadastroUsuActionPerformed
       
    }//GEN-LAST:event_nomeCadastroUsuActionPerformed

    private void cpfCadastroUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfCadastroUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfCadastroUsuActionPerformed

    private void tipoUsuarioCadastroUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoUsuarioCadastroUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoUsuarioCadastroUsuActionPerformed

    private void telefoneCadastroUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneCadastroUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneCadastroUsuActionPerformed

    private void emailCadastroUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailCadastroUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailCadastroUsuActionPerformed

    private void especialidadeCadastroUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadeCadastroUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadeCadastroUsuActionPerformed

    private void crmCadastroUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crmCadastroUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crmCadastroUsuActionPerformed

    private void corenCadastroUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corenCadastroUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corenCadastroUsuActionPerformed

    private void tipoUsuarioCadastroUsuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipoUsuarioCadastroUsuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoUsuarioCadastroUsuKeyPressed

    private void cpfCadastroUsuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfCadastroUsuKeyPressed
        if(evt.getKeyCode() == 10)
            cadastrarUsuario();
    }//GEN-LAST:event_cpfCadastroUsuKeyPressed

    private void nomeCadastroUsuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeCadastroUsuKeyPressed
         if(evt.getKeyCode() == 10)
            cadastrarUsuario();
    }//GEN-LAST:event_nomeCadastroUsuKeyPressed

    private void telefoneCadastroUsuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefoneCadastroUsuKeyPressed
         if(evt.getKeyCode() == 10)
            cadastrarUsuario();
    }//GEN-LAST:event_telefoneCadastroUsuKeyPressed

    private void emailCadastroUsuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailCadastroUsuKeyPressed
        if(evt.getKeyCode() == 10)
            cadastrarUsuario();
    }//GEN-LAST:event_emailCadastroUsuKeyPressed

    private void especialidadeCadastroUsuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_especialidadeCadastroUsuKeyPressed
         if(evt.getKeyCode() == 10)
            cadastrarUsuario();
    }//GEN-LAST:event_especialidadeCadastroUsuKeyPressed

    private void crmCadastroUsuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crmCadastroUsuKeyPressed
        if(evt.getKeyCode() == 10)
            cadastrarUsuario();
    }//GEN-LAST:event_crmCadastroUsuKeyPressed

    private void corenCadastroUsuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_corenCadastroUsuKeyPressed
         if(evt.getKeyCode() == 10)
            cadastrarUsuario();
    }//GEN-LAST:event_corenCadastroUsuKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
         if(evt.getKeyCode() == 10)
            cadastrarUsuario();
    }//GEN-LAST:event_jButton1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
              Cadastro dialog = new Cadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField corenCadastroUsu;
    private javax.swing.JTextField cpfCadastroUsu;
    private javax.swing.JTextField crmCadastroUsu;
    private javax.swing.JTextField emailCadastroUsu;
    private javax.swing.JTextField especialidadeCadastroUsu;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField nomeCadastroUsu;
    private javax.swing.JTextField telefoneCadastroUsu;
    private javax.swing.JLabel textCadastro;
    private javax.swing.JLabel textNomeCadastro;
    private javax.swing.JLabel textSobreNomeCadastro;
    private javax.swing.JLabel textSobreNomeCadastro1;
    private javax.swing.JLabel textSobreNomeCadastro2;
    private javax.swing.JLabel textSobreNomeCadastro3;
    private javax.swing.JLabel textSobreNomeCadastro4;
    private javax.swing.JLabel textTipoUsuarioCadastro;
    private javax.swing.JComboBox<String> tipoUsuarioCadastroUsu;
    private javax.swing.JLabel txtCpfCadastro;
    // End of variables declaration//GEN-END:variables
}
