/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package components;

import AtendimentoHospitalar.Diagnostico;
import AtendimentoHospitalar.Receita;
import Conexao.AtendimentoHospitalarDAO;
import Conexao.PacienteDAO;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import models.Pacientes.Paciente;

/**
 *
 * @author dpaiv
 */
public class ListarInfoPaciente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListarInfoPaciente.class.getName());

    /**
     * Creates new form MenudeRelatorio
     */
    public ListarInfoPaciente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGerarReMenuRel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tipoDeListaListarInfoPaciente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cpfListarInfoPaciente = new javax.swing.JTextField();
        nomeListarInfoPaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtGerarReMenuRel.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        txtGerarReMenuRel.setText("Gerar Listagem do Paciente");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("O que você quer listar?");

        tipoDeListaListarInfoPaciente.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        tipoDeListaListarInfoPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diagnósticos do paciente", "Receitas do paciente" }));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Gerar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("CPF do paciente");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Nome do paciente");

        cpfListarInfoPaciente.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        nomeListarInfoPaciente.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tipoDeListaListarInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtGerarReMenuRel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cpfListarInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(nomeListarInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtGerarReMenuRel)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipoDeListaListarInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cpfListarInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nomeListarInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        setSize(new java.awt.Dimension(916, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gerarListagem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume();
            gerarListagem();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void gerarListagem() {
        try {
            gerarListagemDoBanco();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao gerar listagem: " + e.getMessage());
        }
    }

    private void gerarListagemDoBanco() throws Exception {
        Paciente paciente = buscarPaciente();
        if (paciente == null) {
            throw new Exception("Paciente não encontrado.");
        }

        String opcao = (String) tipoDeListaListarInfoPaciente.getSelectedItem();
        StringBuilder texto = new StringBuilder();
        AtendimentoHospitalarDAO dao = new AtendimentoHospitalarDAO();

        if ("Diagnósticos do paciente".equals(opcao)) {
            for (Diagnostico diagnostico : dao.listarDiagnosticosPorPaciente(paciente.getId())) {
                texto.append("Diagnóstico nº ").append(diagnostico.getId())
                        .append(" - ").append(diagnostico.getDescricao())
                        .append(" - ").append(diagnostico.getDataDiagnostico())
                        .append("\n");
            }
        } else {
            for (Receita receita : dao.listarReceitasPorPaciente(paciente.getId())) {
                texto.append("Receita nº ").append(receita.getId())
                        .append(" - ").append(receita.getPrescricao())
                        .append(" - ").append(receita.getDataEmissao())
                        .append("\n");
            }
        }

        if (texto.length() == 0) {
            texto.append("Nenhum registro encontrado para ").append(paciente.getNome()).append(".");
        }

        JTextArea area = new JTextArea(texto.toString(), 15, 60);
        area.setEditable(false);
        JOptionPane.showMessageDialog(
                this,
                new JScrollPane(area),
                "Dados de " + paciente.getNome(),
                JOptionPane.INFORMATION_MESSAGE);
    }

    private Paciente buscarPaciente() throws Exception {
        PacienteDAO dao = new PacienteDAO();
        String cpf = cpfListarInfoPaciente.getText().trim();
        String nome = nomeListarInfoPaciente.getText().trim();

        if (!cpf.isEmpty()) {
            Paciente paciente = dao.buscarPorCpf(cpf);
            if (paciente != null && (nome.isEmpty() || paciente.getNome().equalsIgnoreCase(nome))) {
                return paciente;
            }
            return null;
        }

        for (Paciente paciente : dao.listar()) {
            if (paciente.getNome().equalsIgnoreCase(nome)) {
                return paciente;
            }
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ListarInfoPaciente dialog = new ListarInfoPaciente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfListarInfoPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomeListarInfoPaciente;
    private javax.swing.JComboBox<String> tipoDeListaListarInfoPaciente;
    private javax.swing.JLabel txtGerarReMenuRel;
    // End of variables declaration//GEN-END:variables
}
