/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package components;

import AtendimentoHospitalar.AplicacaoMedicamento;
import AtendimentoHospitalar.Diagnostico;
import AtendimentoHospitalar.Receita;
import Conexao.AtendimentoHospitalarDAO;
import Conexao.PacienteDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import models.Pacientes.Paciente;
import models.Usuario;

/**
 *
 * @author dpaiv
 */
public class ListarInfoPaciente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListarInfoPaciente.class.getName());
    private Usuario usuarioLogado;

    private interface ExcluirDaTabela {
        void excluir(int id) throws Exception;
    }

    /**
     * Creates new form MenudeRelatorio
     */
    public ListarInfoPaciente(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null);
    }

    public ListarInfoPaciente(java.awt.Frame parent, boolean modal, Usuario usuarioLogado) {
        super(parent, modal);
        initComponents();
        this.usuarioLogado = usuarioLogado;

        // coloca no combo só o que o usuário pode consultar
        tipoDeListaListarInfoPaciente.removeAllItems();
        if (temPerfil("Admin") || temPerfil("Medico")) {
            tipoDeListaListarInfoPaciente.addItem("Diagnósticos do paciente");
        }
        if (temPerfil("Admin") || temPerfil("Medico") || temPerfil("Enfermeiro")) {
            tipoDeListaListarInfoPaciente.addItem("Receitas do paciente");
            tipoDeListaListarInfoPaciente.addItem("Aplicações do paciente");
        }
        jButton1.setEnabled(tipoDeListaListarInfoPaciente.getItemCount() > 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGerarReMenuRel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tipoDeListaListarInfoPaciente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cpfListarInfoPaciente = new javax.swing.JTextField();
        nomeListarInfoPaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtGerarReMenuRel.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        txtGerarReMenuRel.setText("Gerar Listagem do Paciente");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("O que você quer listar?");

        tipoDeListaListarInfoPaciente.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        tipoDeListaListarInfoPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Gerar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("CPF do paciente");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Nome do paciente");

        cpfListarInfoPaciente.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        nomeListarInfoPaciente.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tipoDeListaListarInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtGerarReMenuRel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cpfListarInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(nomeListarInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtGerarReMenuRel)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipoDeListaListarInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cpfListarInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nomeListarInfoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        setSize(new java.awt.Dimension(916, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gerarListagem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume();
            gerarListagem();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void gerarListagem() {
        try {
            gerarListagemDoBanco();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao gerar listagem: " + e.getMessage());
        }
    }

    private void gerarListagemDoBanco() throws Exception {
        Paciente paciente = buscarPaciente();
        if (paciente == null) {
            throw new Exception("Paciente não encontrado.");
        }

        String opcao = (String) tipoDeListaListarInfoPaciente.getSelectedItem();

        if (opcao == null) {
            throw new Exception("Usuário sem permissão para consultar dados do paciente.");
        } else if ("Diagnósticos do paciente".equals(opcao)) {
            listarDiagnosticos(paciente);
        } else if ("Receitas do paciente".equals(opcao)) {
            listarReceitas(paciente);
        } else if ("Aplicações do paciente".equals(opcao)) {
            listarAplicacoes(paciente);
        } else {
            throw new Exception("Consulta não permitida para este usuário.");
        }
    }

    private void listarDiagnosticos(Paciente paciente) throws Exception {
        if (!temPerfil("Admin") && !temPerfil("Medico")) {
            throw new Exception("Este perfil não pode listar diagnósticos.");
        }

        AtendimentoHospitalarDAO dao = new AtendimentoHospitalarDAO();
        List<Diagnostico> diagnosticos = dao.listarDiagnosticosPorPaciente(paciente.getId());
        Object[][] dados = new Object[diagnosticos.size()][4];

        for (int i = 0; i < diagnosticos.size(); i++) {
            Diagnostico diagnostico = diagnosticos.get(i);
            dados[i][0] = diagnostico.getId();
            dados[i][1] = diagnostico.getDescricao();
            dados[i][2] = diagnostico.getObservacoes();
            dados[i][3] = diagnostico.getDataDiagnostico();
        }

        mostrarTabela(
                "Diagnósticos de " + paciente.getNome(),
                new String[]{"ID", "Diagnóstico", "Observações", "Data"},
                dados,
                temPerfil("Medico"),
                dao::excluirDiagnostico);
    }

    private void listarReceitas(Paciente paciente) throws Exception {
        if (!temPerfil("Admin") && !temPerfil("Medico") && !temPerfil("Enfermeiro")) {
            throw new Exception("Este perfil não pode listar medicamentos do paciente.");
        }

        AtendimentoHospitalarDAO dao = new AtendimentoHospitalarDAO();
        List<Receita> receitas = dao.listarReceitasPorPaciente(paciente.getId());
        Object[][] dados = new Object[receitas.size()][4];

        for (int i = 0; i < receitas.size(); i++) {
            Receita receita = receitas.get(i);
            dados[i][0] = receita.getId();
            dados[i][1] = receita.getPrescricao();
            dados[i][2] = receita.isAplicarNoHospital() ? "Sim" : "Não";
            dados[i][3] = receita.getDataEmissao();
        }

        mostrarTabela(
                "Receitas de " + paciente.getNome(),
                new String[]{"ID", "Prescrição", "Aplicar no hospital", "Data"},
                dados,
                temPerfil("Medico"),
                dao::excluirReceita);
    }

    private void listarAplicacoes(Paciente paciente) throws Exception {
        if (!temPerfil("Admin") && !temPerfil("Medico") && !temPerfil("Enfermeiro")) {
            throw new Exception("Este perfil não pode listar medicamentos do paciente.");
        }

        AtendimentoHospitalarDAO dao = new AtendimentoHospitalarDAO();
        List<AplicacaoMedicamento> aplicacoes = dao.listarAplicacoesPorPaciente(paciente.getId());
        Object[][] dados = new Object[aplicacoes.size()][5];

        for (int i = 0; i < aplicacoes.size(); i++) {
            AplicacaoMedicamento aplicacao = aplicacoes.get(i);
            dados[i][0] = aplicacao.getId();
            dados[i][1] = aplicacao.getReceitaId();
            dados[i][2] = aplicacao.getDosagemAplicada();
            dados[i][3] = aplicacao.getViaAplicacao();
            dados[i][4] = aplicacao.getDataAplicacao();
        }

        mostrarTabela(
                "Aplicações de " + paciente.getNome(),
                new String[]{"ID", "Receita", "Dosagem", "Via", "Data"},
                dados,
                temPerfil("Enfermeiro"),
                dao::excluirAplicacao);
    }

    private void mostrarTabela(String titulo, String[] colunas, Object[][] dados,
            boolean podeExcluir, ExcluirDaTabela acaoExcluir) {

        DefaultTableModel modelo = new DefaultTableModel(dados, colunas) {
            @Override
            public boolean isCellEditable(int linha, int coluna) {
                return false;
            }
        };

        JTable tabela = new JTable(modelo);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        JScrollPane painelTabela = new JScrollPane(tabela);
        painelTabela.setPreferredSize(new java.awt.Dimension(750, 350));

        if (!podeExcluir) {
            JOptionPane.showMessageDialog(this, painelTabela, titulo, JOptionPane.PLAIN_MESSAGE);
            return;
        }

        Object[] botoes = {"Excluir selecionado", "Fechar"};
        boolean continuar = true;

        while (continuar) {
            int opcao = JOptionPane.showOptionDialog(
                    this, painelTabela, titulo, JOptionPane.DEFAULT_OPTION,
                    JOptionPane.PLAIN_MESSAGE, null, botoes, botoes[1]);

            if (opcao != 0) {
                continuar = false;
            } else if (tabela.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Selecione uma linha para excluir.");
            } else {
                int confirmar = JOptionPane.showConfirmDialog(
                        this,
                        "Deseja realmente excluir o registro selecionado?",
                        "Confirmar exclusão",
                        JOptionPane.YES_NO_OPTION);

                if (confirmar == JOptionPane.YES_OPTION) {
                    try {
                        int linha = tabela.getSelectedRow();
                        int id = ((Number) modelo.getValueAt(linha, 0)).intValue();
                        acaoExcluir.excluir(id);
                        modelo.removeRow(linha);
                        JOptionPane.showMessageDialog(this, "Registro excluído.");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
                    }
                }
            }
        }
    }

    private boolean temPerfil(String perfil) {
        return usuarioLogado != null
                && usuarioLogado.getPerfil() != null
                && usuarioLogado.getPerfil().equalsIgnoreCase(perfil);
    }

    private Paciente buscarPaciente() throws Exception {
        PacienteDAO dao = new PacienteDAO();
        String cpf = cpfListarInfoPaciente.getText().trim();
        String nome = nomeListarInfoPaciente.getText().trim();

        if (!cpf.isEmpty()) {
            Paciente paciente = dao.buscarPorCpf(cpf);
            if (paciente != null && (nome.isEmpty() || paciente.getNome().equalsIgnoreCase(nome))) {
                return paciente;
            }
            return null;
        }

        for (Paciente paciente : dao.listar()) {
            if (paciente.getNome().equalsIgnoreCase(nome)) {
                return paciente;
            }
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ListarInfoPaciente dialog = new ListarInfoPaciente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfListarInfoPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomeListarInfoPaciente;
    private javax.swing.JComboBox<String> tipoDeListaListarInfoPaciente;
    private javax.swing.JLabel txtGerarReMenuRel;
    // End of variables declaration//GEN-END:variables
}
