/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package components;

/**
 *
 * @author dpaiv
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_label = new javax.swing.JLabel();
        login_senha = new javax.swing.JPasswordField();
        login_usu = new javax.swing.JTextField();
        text_login = new javax.swing.JLabel();
        text_senha = new javax.swing.JLabel();
        Botao_login = new javax.swing.JToggleButton();
        mostrar_senha = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login_label.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        login_label.setText("Login");

        login_senha.addActionListener(this::senha_usu);

        login_usu.addActionListener(this::login_usu);

        text_login.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_login.setText("Usuario");

        text_senha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_senha.setText("Senha");

        Botao_login.setText("Enter");
        Botao_login.addActionListener(this::botao_enter);

        mostrar_senha.setText("Mostrar senha");
        mostrar_senha.addActionListener(this::mostrar_senhaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_login)
                            .addComponent(text_senha))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(login_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(login_usu)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(login_label)))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mostrar_senha)
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Botao_login, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(login_label)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_login))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_senha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(mostrar_senha)
                .addGap(29, 29, 29)
                .addComponent(Botao_login)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_usu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_usu
        // TODO add your handling code here:
    }//GEN-LAST:event_login_usu

    private void senha_usu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senha_usu
            // TODO add your handling code here:
    }//GEN-LAST:event_senha_usu

    private void botao_enter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_enter
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_enter

    private void mostrar_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrar_senhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Botao_login;
    private javax.swing.JLabel login_label;
    private javax.swing.JPasswordField login_senha;
    private javax.swing.JTextField login_usu;
    private javax.swing.JCheckBox mostrar_senha;
    private javax.swing.JLabel text_login;
    private javax.swing.JLabel text_senha;
    // End of variables declaration//GEN-END:variables
}
