/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package components;

import Conexao.EnfermeiroDAO;
import Conexao.MedicoDAO;
import Conexao.PacienteDAO;
import Conexao.UsuarioDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import models.Funcionarios.Enfermeiro;
import models.Funcionarios.Medico;
import models.Pacientes.Paciente;
import models.Usuario;

/**
 *
 * @author dpaiv
 */
public class MenuListagem extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuListagem.class.getName());
    private Usuario usuarioLogado;

    private interface ExcluirDaTabela {
        void excluir(int id) throws Exception;
    }

    /**
     * Creates new form MenudeRelatorio
     */
    public MenuListagem(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null);
    }

    public MenuListagem(java.awt.Frame parent, boolean modal, Usuario usuarioLogado) {
        super(parent, modal);
        initComponents();
        this.usuarioLogado = usuarioLogado;

        // cada tipo de usuário vê somente as listas dele
        tipoDeListaMenuListagem.removeAllItems();
        if (temPerfil("Admin")) {
            tipoDeListaMenuListagem.addItem("Todos Médicos");
            tipoDeListaMenuListagem.addItem("Todos Enfermeiros");
            tipoDeListaMenuListagem.addItem("Todos Pacientes");
            tipoDeListaMenuListagem.addItem("Dados do paciente");
            tipoDeListaMenuListagem.addItem("Todos Usuários");
        } else if (temPerfil("Medico") || temPerfil("Enfermeiro")) {
            tipoDeListaMenuListagem.addItem("Todos Pacientes");
            tipoDeListaMenuListagem.addItem("Dados do paciente");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGerarReMenuRel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tipoDeListaMenuListagem = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtGerarReMenuRel.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        txtGerarReMenuRel.setText("Gerar Listagem");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("O que você quer listar?");

        tipoDeListaMenuListagem.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        tipoDeListaMenuListagem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        tipoDeListaMenuListagem.addActionListener(this::tipoDeListaMenuListagemActionPerformed);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Gerar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tipoDeListaMenuListagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtGerarReMenuRel))
                .addContainerGap(443, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtGerarReMenuRel)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipoDeListaMenuListagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        setSize(new java.awt.Dimension(916, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tipoDeListaMenuListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDeListaMenuListagemActionPerformed
        jButton1.requestFocusInWindow();
    }//GEN-LAST:event_tipoDeListaMenuListagemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gerarListagem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume();
            gerarListagem();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void gerarListagem() {
        try {
            gerarListagemDoBanco();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao gerar listagem: " + e.getMessage());
        }
    }

    private void gerarListagemDoBanco() throws Exception {
        Object itemEscolhido = tipoDeListaMenuListagem.getSelectedItem();
        if (itemEscolhido == null) {
            throw new Exception("Usuário sem permissão para realizar listagens.");
        }
        String opcao = itemEscolhido.toString();

        if ("Dados do paciente".equals(opcao)) {
            new ListarInfoPaciente(null, true, usuarioLogado).setVisible(true);
            return;
        }

        if ("Todos Médicos".equals(opcao)) {
            listarMedicos();
        } else if ("Todos Enfermeiros".equals(opcao)) {
            listarEnfermeiros();
        } else if ("Todos Pacientes".equals(opcao)) {
            listarPacientes();
        } else if ("Todos Usuários".equals(opcao)) {
            listarUsuarios();
        } else {
            throw new Exception("Listagem não permitida para este usuário.");
        }
    }

    private void listarMedicos() throws Exception {
        if (!temPerfil("Admin")) {
            throw new Exception("Apenas administradores podem listar médicos.");
        }

        ArrayList<Medico> medicos = new MedicoDAO().listar();
        Object[][] dados = new Object[medicos.size()][4];

        for (int i = 0; i < medicos.size(); i++) {
            Medico medico = medicos.get(i);
            dados[i][0] = medico.getId();
            dados[i][1] = medico.getNome();
            dados[i][2] = medico.getCrm();
            dados[i][3] = medico.getEspecialidade();
        }

        mostrarTabela(
                "Médicos",
                new String[]{"ID", "Nome", "CRM", "Especialidade"},
                dados,
                false,
                null);
    }

    private void listarEnfermeiros() throws Exception {
        if (!temPerfil("Admin")) {
            throw new Exception("Apenas administradores podem listar enfermeiros.");
        }

        ArrayList<Enfermeiro> enfermeiros = new EnfermeiroDAO().listar();
        Object[][] dados = new Object[enfermeiros.size()][3];

        for (int i = 0; i < enfermeiros.size(); i++) {
            Enfermeiro enfermeiro = enfermeiros.get(i);
            dados[i][0] = enfermeiro.getId();
            dados[i][1] = enfermeiro.getNome();
            dados[i][2] = enfermeiro.getCoren();
        }

        mostrarTabela(
                "Enfermeiros",
                new String[]{"ID", "Nome", "Coren"},
                dados,
                false,
                null);
    }

    private void listarPacientes() throws Exception {
        if (!temPerfil("Admin") && !temPerfil("Medico") && !temPerfil("Enfermeiro")) {
            throw new Exception("Usuário sem permissão para listar pacientes.");
        }

        PacienteDAO dao = new PacienteDAO();
        ArrayList<Paciente> pacientes = dao.listar();
        Object[][] dados = new Object[pacientes.size()][5];

        for (int i = 0; i < pacientes.size(); i++) {
            Paciente paciente = pacientes.get(i);
            dados[i][0] = paciente.getId();
            dados[i][1] = paciente.getNome();
            dados[i][2] = paciente.getCpf();
            dados[i][3] = paciente.getDataNascimento();
            dados[i][4] = paciente.getTelefone();
        }

        boolean podeExcluir = temPerfil("Medico") || temPerfil("Enfermeiro");
        mostrarTabela(
                "Pacientes",
                new String[]{"ID", "Nome", "CPF", "Nascimento", "Telefone"},
                dados,
                podeExcluir,
                dao::excluir);
    }

    private void listarUsuarios() throws Exception {
        if (!temPerfil("Admin")) {
            throw new Exception("Apenas administradores podem listar usuários.");
        }

        UsuarioDAO dao = new UsuarioDAO();
        ArrayList<Usuario> usuarios = dao.Listar();
        Object[][] dados = new Object[usuarios.size()][4];

        for (int i = 0; i < usuarios.size(); i++) {
            Usuario usuario = usuarios.get(i);
            dados[i][0] = usuario.getId();
            dados[i][1] = usuario.getEmail();
            dados[i][2] = usuario.getPerfil();
            dados[i][3] = Boolean.TRUE.equals(usuario.getAtivo()) ? "Sim" : "Não";
        }

        mostrarTabela(
                "Usuários",
                new String[]{"ID", "Email", "Perfil", "Ativo"},
                dados,
                true,
                id -> {
                    if (usuarioLogado != null && usuarioLogado.getId() == id) {
                        throw new Exception("O administrador não pode excluir o próprio usuário.");
                    }
                    dao.excluir(id);
                });
    }

    private void mostrarTabela(String titulo, String[] colunas, Object[][] dados,
            boolean podeExcluir, ExcluirDaTabela acaoExcluir) {

        DefaultTableModel modelo = new DefaultTableModel(dados, colunas) {
            @Override
            public boolean isCellEditable(int linha, int coluna) {
                return false;
            }
        };

        JTable tabela = new JTable(modelo);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        JScrollPane painelTabela = new JScrollPane(tabela);
        painelTabela.setPreferredSize(new java.awt.Dimension(750, 350));

        if (!podeExcluir) {
            JOptionPane.showMessageDialog(this, painelTabela, titulo, JOptionPane.PLAIN_MESSAGE);
            return;
        }

        Object[] botoes = {"Excluir selecionado", "Fechar"};
        boolean continuar = true;

        while (continuar) {
            int opcao = JOptionPane.showOptionDialog(
                    this, painelTabela, titulo, JOptionPane.DEFAULT_OPTION,
                    JOptionPane.PLAIN_MESSAGE, null, botoes, botoes[1]);

            if (opcao != 0) {
                continuar = false;
            } else if (tabela.getSelectedRow() < 0) {
                JOptionPane.showMessageDialog(this, "Selecione uma linha para excluir.");
            } else {
                int confirmar = JOptionPane.showConfirmDialog(
                        this,
                        "Deseja realmente excluir o registro selecionado?",
                        "Confirmar exclusão",
                        JOptionPane.YES_NO_OPTION);

                if (confirmar == JOptionPane.YES_OPTION) {
                    try {
                        int linha = tabela.getSelectedRow();
                        int id = ((Number) modelo.getValueAt(linha, 0)).intValue();
                        acaoExcluir.excluir(id);
                        modelo.removeRow(linha);
                        JOptionPane.showMessageDialog(this, "Registro excluído.");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
                    }
                }
            }
        }
    }

    private boolean temPerfil(String perfil) {
        return usuarioLogado != null
                && usuarioLogado.getPerfil() != null
                && usuarioLogado.getPerfil().equalsIgnoreCase(perfil);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MenuListagem dialog = new MenuListagem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> tipoDeListaMenuListagem;
    private javax.swing.JLabel txtGerarReMenuRel;
    // End of variables declaration//GEN-END:variables
}
