/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package components;

import Conexao.EnfermeiroDAO;
import Conexao.MedicoDAO;
import Conexao.PacienteDAO;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import models.Funcionarios.Enfermeiro;
import models.Funcionarios.Medico;
import models.Pacientes.Paciente;

/**
 *
 * @author dpaiv
 */
public class MenuListagem extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuListagem.class.getName());

    /**
     * Creates new form MenudeRelatorio
     */
    public MenuListagem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtGerarReMenuRel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tipoDeListaMenuListagem = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtGerarReMenuRel.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        txtGerarReMenuRel.setText("Gerar Listagem");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("O que você quer listar?");

        tipoDeListaMenuListagem.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        tipoDeListaMenuListagem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos Médicos", "Todos Enfermeiros", "Todos Pacientes", "Diagnósticos/Receitas do paciente" }));
        tipoDeListaMenuListagem.addActionListener(this::tipoDeListaMenuListagemActionPerformed);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Gerar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tipoDeListaMenuListagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtGerarReMenuRel))
                .addContainerGap(443, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtGerarReMenuRel)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipoDeListaMenuListagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        setSize(new java.awt.Dimension(916, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tipoDeListaMenuListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDeListaMenuListagemActionPerformed
        jButton1.requestFocusInWindow();
    }//GEN-LAST:event_tipoDeListaMenuListagemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gerarListagem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume();
            gerarListagem();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void gerarListagem() {
        try {
            gerarListagemDoBanco();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao gerar listagem: " + e.getMessage());
        }
    }

    private void gerarListagemDoBanco() throws Exception {
        String opcao = (String) tipoDeListaMenuListagem.getSelectedItem();

        if ("Diagnósticos/Receitas do paciente".equals(opcao)) {
            new ListarInfoPaciente(null, true).setVisible(true);
            return;
        }

        StringBuilder texto = new StringBuilder();

        if ("Todos Médicos".equals(opcao)) {
            for (Medico medico : new MedicoDAO().listar()) {
                texto.append("ID: ").append(medico.getId())
                        .append(" | Nome: ").append(medico.getNome())
                        .append(" | CRM: ").append(medico.getCrm())
                        .append(" | Especialidade: ").append(medico.getEspecialidade())
                        .append("\n");
            }
        } else if ("Todos Enfermeiros".equals(opcao)) {
            for (Enfermeiro enfermeiro : new EnfermeiroDAO().listar()) {
                texto.append("ID: ").append(enfermeiro.getId())
                        .append(" | Nome: ").append(enfermeiro.getNome())
                        .append(" | Coren: ").append(enfermeiro.getCoren())
                        .append("\n");
            }
        } else if ("Todos Pacientes".equals(opcao)) {
            for (Paciente paciente : new PacienteDAO().listar()) {
                texto.append("ID: ").append(paciente.getId())
                        .append(" | Nome: ").append(paciente.getNome())
                        .append(" | CPF: ").append(paciente.getCpf())
                        .append("\n");
            }
        }

        if (texto.length() == 0) {
            texto.append("Nenhum registro encontrado.");
        }

        JTextArea area = new JTextArea(texto.toString(), 15, 60);
        area.setEditable(false);
        JOptionPane.showMessageDialog(
                this,
                new JScrollPane(area),
                "Listagem",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MenuListagem dialog = new MenuListagem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> tipoDeListaMenuListagem;
    private javax.swing.JLabel txtGerarReMenuRel;
    // End of variables declaration//GEN-END:variables
}
