/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package components;

import AtendimentoHospitalar.Diagnostico;
import Conexao.AtendimentoHospitalarDAO;
import Conexao.PacienteDAO;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import models.Pacientes.Paciente;
import models.Usuario;

/**
 *
 * @author dpaiv
 */
public class RegistrarDiagnostico extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarDiagnostico.class.getName());
    private final AtendimentoHospitalarDAO atendimentoDAO = new AtendimentoHospitalarDAO();
    private final PacienteDAO pacienteDAO = new PacienteDAO();
    private Usuario medico;

    /**
     * Creates new form MenuMedico
     */
    public RegistrarDiagnostico(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null);
    }

    public RegistrarDiagnostico(java.awt.Frame parent, boolean modal, Usuario medico) {
        super(parent, modal);
        initComponents();
        this.medico = medico;
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDrMenu = new javax.swing.JLabel();
        textFuncMenuDr = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textFuncMenuDr1 = new javax.swing.JLabel();
        textFuncMenuDr2 = new javax.swing.JLabel();
        cpfRegistrarDiagnostico = new javax.swing.JTextField();
        nomeRegistrarDiagnostico = new javax.swing.JTextField();
        idRegistrarDiagnostico = new javax.swing.JTextField();
        textFuncMenuDr3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        diagnosticoRegistrarDiagnostico = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtDrMenu.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        txtDrMenu.setText("Registrar diagnostico");
        txtDrMenu.setToolTipText("");

        textFuncMenuDr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textFuncMenuDr.setText("Nome do paciente");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        textFuncMenuDr1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textFuncMenuDr1.setText("ID paciente");

        textFuncMenuDr2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textFuncMenuDr2.setText("CPF paciente");

        cpfRegistrarDiagnostico.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        nomeRegistrarDiagnostico.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        nomeRegistrarDiagnostico.addActionListener(this::nomeRegistrarDiagnosticoActionPerformed);

        idRegistrarDiagnostico.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        textFuncMenuDr3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textFuncMenuDr3.setText("Diagnostico:");

        diagnosticoRegistrarDiagnostico.setColumns(20);
        diagnosticoRegistrarDiagnostico.setRows(5);
        jScrollPane1.setViewportView(diagnosticoRegistrarDiagnostico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFuncMenuDr2)
                                .addGap(18, 18, 18)
                                .addComponent(cpfRegistrarDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDrMenu)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFuncMenuDr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeRegistrarDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFuncMenuDr1)
                                .addGap(18, 18, 18)
                                .addComponent(idRegistrarDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFuncMenuDr3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtDrMenu)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFuncMenuDr2)
                    .addComponent(cpfRegistrarDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFuncMenuDr)
                    .addComponent(nomeRegistrarDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFuncMenuDr1)
                    .addComponent(idRegistrarDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFuncMenuDr3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        setBounds(0, 0, 916, 509);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registrarDiagnostico();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nomeRegistrarDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeRegistrarDiagnosticoActionPerformed
        diagnosticoRegistrarDiagnostico.requestFocusInWindow();
    }//GEN-LAST:event_nomeRegistrarDiagnosticoActionPerformed

    private void registrarDiagnostico() {
        try {
            int pacienteId = Integer.parseInt(idRegistrarDiagnostico.getText().trim());
            Paciente paciente = pacienteDAO.buscar(pacienteId);
            if (paciente == null) {
                throw new Exception("Paciente não encontrado.");
            }

            String cpfInformado = cpfRegistrarDiagnostico.getText().replaceAll("\\D", "");
            if (!paciente.getCpf().equals(cpfInformado)) {
                throw new Exception("O CPF não pertence ao paciente informado.");
            }

            String nomeInformado = nomeRegistrarDiagnostico.getText().trim();
            if (!paciente.getNome().equalsIgnoreCase(nomeInformado)) {
                throw new Exception("O nome não pertence ao paciente informado.");
            }

            Diagnostico diagnostico = new Diagnostico();
            diagnostico.setPacienteId(paciente.getId());
            diagnostico.setPacienteCpf(paciente.getCpf());
            diagnostico.setPacienteNome(paciente.getNome());
            diagnostico.setDescricao(diagnosticoRegistrarDiagnostico.getText().trim());
            diagnostico.setDataDiagnostico(LocalDateTime.now());

            if (medico != null) {
                diagnostico.setMedicoId(medico.getFuncionarioId());
            }

            Integer idDiagnostico = atendimentoDAO.salvarDiagnostico(diagnostico);

            JOptionPane.showMessageDialog(
                    this,
                    "Diagnóstico nº " + idDiagnostico + " registrado.",
                    "Diagnóstico registrado",
                    JOptionPane.INFORMATION_MESSAGE);

            limparCampos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "ID do paciente deve ser um número inteiro positivo.",
                    "Dados inválidos",
                    JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    e.getMessage(),
                    "Não foi possível registrar o diagnóstico",
                    JOptionPane.WARNING_MESSAGE);
        }
    }

    private void limparCampos() {
        cpfRegistrarDiagnostico.setText("");
        nomeRegistrarDiagnostico.setText("");
        idRegistrarDiagnostico.setText("");
        diagnosticoRegistrarDiagnostico.setText("");
        cpfRegistrarDiagnostico.requestFocusInWindow();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RegistrarDiagnostico dialog = new RegistrarDiagnostico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cpfRegistrarDiagnostico;
    private javax.swing.JTextArea diagnosticoRegistrarDiagnostico;
    private javax.swing.JTextField idRegistrarDiagnostico;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeRegistrarDiagnostico;
    private javax.swing.JLabel textFuncMenuDr;
    private javax.swing.JLabel textFuncMenuDr1;
    private javax.swing.JLabel textFuncMenuDr2;
    private javax.swing.JLabel textFuncMenuDr3;
    private javax.swing.JLabel txtDrMenu;
    // End of variables declaration//GEN-END:variables
}
