/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package components;

import AtendimentoHospitalar.AplicacaoMedicamento;

/**
 *
 * @author dpaiv
 */
public class RegistrarReceita extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarReceita.class.getName());

    /**
     * Creates new form MenuMedico
     */
    public RegistrarReceita(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDrMenu = new javax.swing.JLabel();
        textFuncMenuDr = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textFuncMenuDr1 = new javax.swing.JLabel();
        textFuncMenuDr2 = new javax.swing.JLabel();
        cpfRegistrarReceita = new javax.swing.JTextField();
        nomeRegistrarReceita = new javax.swing.JTextField();
        idRegistrarReceita = new javax.swing.JTextField();
        textFuncMenuDr3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReceitaRegistrarReceita = new javax.swing.JTextArea();
        textFuncMenuDr4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtDrMenu.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        txtDrMenu.setText("Registrar Recita");
        txtDrMenu.setToolTipText("");

        textFuncMenuDr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textFuncMenuDr.setText("Nome do paciente");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        textFuncMenuDr1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textFuncMenuDr1.setText("ID paciente");

        textFuncMenuDr2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textFuncMenuDr2.setText("CPF paciente");

        cpfRegistrarReceita.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        nomeRegistrarReceita.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N

        idRegistrarReceita.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        idRegistrarReceita.addActionListener(this::idRegistrarReceitaActionPerformed);

        textFuncMenuDr3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textFuncMenuDr3.setText("Receita:");

        ReceitaRegistrarReceita.setColumns(20);
        ReceitaRegistrarReceita.setRows(5);
        jScrollPane1.setViewportView(ReceitaRegistrarReceita);

        textFuncMenuDr4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textFuncMenuDr4.setText("Aplicar no hospital?");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel1.setText("Caso tenha algum medicamento enjetavel");

        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jRadioButton1.setText("Sim");
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFuncMenuDr2)
                                .addGap(18, 18, 18)
                                .addComponent(cpfRegistrarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDrMenu)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFuncMenuDr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nomeRegistrarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFuncMenuDr1)
                                .addGap(18, 18, 18)
                                .addComponent(idRegistrarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFuncMenuDr4)
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton1)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)))
                        .addContainerGap(383, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textFuncMenuDr3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtDrMenu)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFuncMenuDr2)
                    .addComponent(cpfRegistrarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFuncMenuDr)
                    .addComponent(nomeRegistrarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFuncMenuDr1)
                    .addComponent(idRegistrarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFuncMenuDr4)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFuncMenuDr3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        setBounds(0, 0, 916, 509);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void idRegistrarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idRegistrarReceitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idRegistrarReceitaActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RegistrarReceita dialog = new RegistrarReceita(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ReceitaRegistrarReceita;
    private javax.swing.JTextField cpfRegistrarReceita;
    private javax.swing.JTextField idRegistrarReceita;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeRegistrarReceita;
    private javax.swing.JLabel textFuncMenuDr;
    private javax.swing.JLabel textFuncMenuDr1;
    private javax.swing.JLabel textFuncMenuDr2;
    private javax.swing.JLabel textFuncMenuDr3;
    private javax.swing.JLabel textFuncMenuDr4;
    private javax.swing.JLabel txtDrMenu;
    // End of variables declaration//GEN-END:variables
}
