/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package components;

import Conexao.UsuarioDAO;
import java.util.Arrays;
import javax.swing.JOptionPane;
import models.Usuario;
import utils.Criptografia;

/**
 *
 * @author dpaiv
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        getRootPane().setDefaultButton(jButton1);
        try {
            criarAdminInicial();
        } catch (Exception ex) {
            logger.log(
                    java.util.logging.Level.FINE,
                    "Inicialização do administrador adiada até o banco estar disponível.",
                    ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textUsuarioLogin = new javax.swing.JLabel();
        usuarioLogin = new javax.swing.JTextField();
        textSenhaLogin = new javax.swing.JLabel();
        senhaUsuarioLogin = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        boxMostrarSenha = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        jLabel1.setFocusable(false);

        textUsuarioLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textUsuarioLogin.setText("Usuario:");

        usuarioLogin.setMinimumSize(new java.awt.Dimension(62, 22));
        usuarioLogin.setPreferredSize(new java.awt.Dimension(50, 20));
        usuarioLogin.addActionListener(this::usuarioLoginActionPerformed);
        usuarioLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioLoginKeyPressed(evt);
            }
        });

        textSenhaLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSenhaLogin.setText("Senha:");

        senhaUsuarioLogin.setPreferredSize(new java.awt.Dimension(50, 20));
        senhaUsuarioLogin.addActionListener(this::senhaUsuarioLoginActionPerformed);
        senhaUsuarioLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhaUsuarioLoginKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        boxMostrarSenha.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        boxMostrarSenha.setText("Mostrar senha");
        boxMostrarSenha.addActionListener(this::boxMostrarSenhaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textUsuarioLogin)
                            .addComponent(textSenhaLogin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(459, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boxMostrarSenha)
                        .addGap(336, 336, 336))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUsuarioLogin)
                    .addComponent(usuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSenhaLogin)
                    .addComponent(senhaUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(boxMostrarSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        setSize(new java.awt.Dimension(916, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Logar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioLoginActionPerformed
        senhaUsuarioLogin.requestFocusInWindow();
    }//GEN-LAST:event_usuarioLoginActionPerformed

    private void senhaUsuarioLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaUsuarioLoginActionPerformed
        Logar();
    }//GEN-LAST:event_senhaUsuarioLoginActionPerformed

    private void usuarioLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioLoginKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume();
            Logar();
        }
    }//GEN-LAST:event_usuarioLoginKeyPressed

    private void senhaUsuarioLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaUsuarioLoginKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume();
            Logar();
        }
    }//GEN-LAST:event_senhaUsuarioLoginKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume();
            Logar();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void boxMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMostrarSenhaActionPerformed
       if(boxMostrarSenha.isSelected())
            senhaUsuarioLogin.setEchoChar((char) 0);
        else
            senhaUsuarioLogin.setEchoChar('*');
    }//GEN-LAST:event_boxMostrarSenhaActionPerformed
    
   private void Logar()
    {
        String login = usuarioLogin.getText().trim();
        char[] senha = senhaUsuarioLogin.getPassword();

        if (login.length() < 3) {
            JOptionPane.showMessageDialog(this, "Email de usuário inválido.");
            usuarioLogin.requestFocusInWindow();
            return;
        }
        
        if (senha.length < 3) {
            JOptionPane.showMessageDialog(this, "Senha do usuário inválida.");
            senhaUsuarioLogin.requestFocusInWindow();
            Arrays.fill(senha, '\0');
            return;
        }
        
        try {
            Criptografia crip = new Criptografia();
            String hashedPassword = crip.criptografar(senha);
            UsuarioDAO dao = new UsuarioDAO();
            Usuario user = dao.Autenticar(login, hashedPassword);
            if (user == null) {
                JOptionPane.showMessageDialog(this, "Erro: Credencial inválida");
                return;
            }

            if (Boolean.TRUE.equals(user.getDeveTrocarSenha())) {
                TrocarSenha telaTrocarSenha = new TrocarSenha(user);
                telaTrocarSenha.setVisible(true);
                this.dispose();
                return;
            }

            String perfil = user.getPerfil();
            if (perfil == null) {
                JOptionPane.showMessageDialog(this, "Usuário sem perfil de acesso.");
                return;
            }

            if (perfil.equalsIgnoreCase("Medico")) {
                MenuMedico telaMedico = new MenuMedico(user);
                telaMedico.setVisible(true);
                this.dispose();
            } else if (perfil.equalsIgnoreCase("Enfermeiro")) {
                MenuEnfermeiro telaEnfermeiro = new MenuEnfermeiro(user);
                telaEnfermeiro.setVisible(true);
                this.dispose();
            } else if (perfil.equalsIgnoreCase("Admin")) {
                MenuAdm telaAdmin = new MenuAdm(user);
                telaAdmin.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Perfil de acesso desconhecido: " + perfil);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: "+ e.getMessage());
        } finally {
            Arrays.fill(senha, '\0');
        }
        
    }
   
   public void criarAdminInicial() throws Exception {
    UsuarioDAO usuarioDAO = new UsuarioDAO();

    if (usuarioDAO.existeAdmin()) {
        return;
    }

    Criptografia crip = new Criptografia();

    char[] senha = "admin123".toCharArray();
    String senhaHash = crip.criptografar(senha);

    Usuario admin = new Usuario();

    admin.setFuncionarioId(null);
    admin.setEmail("admin@sistema.com");
    admin.setSenhaHash(senhaHash);
    admin.setPerfil("ADMIN");
    admin.setDeveTrocarSenha(true);
    admin.setAtivo(true);

    usuarioDAO.Cadastrar(admin);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new TelaLogin().setVisible(true);
            } catch (Exception ex) {
                System.getLogger(TelaLogin.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox boxMostrarSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField senhaUsuarioLogin;
    private javax.swing.JLabel textSenhaLogin;
    private javax.swing.JLabel textUsuarioLogin;
    private javax.swing.JTextField usuarioLogin;
    // End of variables declaration//GEN-END:variables
}
