/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package components;

import Conexao.UsuarioDAO;
import java.util.Arrays;
import javax.swing.JOptionPane;
import models.Usuario;
import utils.Criptografia;

/**
 *
 * @author eduardo-silva
 */
public class TrocarSenha extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TrocarSenha.class.getName());
    private final UsuarioDAO userChangeHashPass = new UsuarioDAO();
    private Usuario u;
    /**
     * Creates new form TrocarSenha
     */
    public TrocarSenha(Usuario u) {
        initComponents();
        this.u = u;
        getRootPane().setDefaultButton(trocarSenha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputTrocarSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        trocarSenha = new javax.swing.JButton();
        checkMostrarSenha = new javax.swing.JCheckBox();
        Finalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputTrocarSenha.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        inputTrocarSenha.addActionListener(this::inputTrocarSenhaActionPerformed);
        inputTrocarSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputTrocarSenhaKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Nova senha:");

        trocarSenha.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        trocarSenha.setText("Trocar");
        trocarSenha.addActionListener(this::trocarSenhaActionPerformed);
        trocarSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                trocarSenhaKeyPressed(evt);
            }
        });

        checkMostrarSenha.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        checkMostrarSenha.setText("Mostrar senha");
        checkMostrarSenha.addActionListener(this::checkMostrarSenhaActionPerformed);

        Finalizar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Finalizar.setText("Finalizar");
        Finalizar.addActionListener(this::FinalizarActionPerformed);
        Finalizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FinalizarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(inputTrocarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(checkMostrarSenha)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(trocarSenha)
                        .addGap(76, 76, 76)
                        .addComponent(Finalizar)
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTrocarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(checkMostrarSenha)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trocarSenha)
                    .addComponent(Finalizar))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTrocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTrocarSenhaActionPerformed
        alterarSenha();
    }//GEN-LAST:event_inputTrocarSenhaActionPerformed

    private void trocarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocarSenhaActionPerformed
        alterarSenha();
    }//GEN-LAST:event_trocarSenhaActionPerformed

    private void inputTrocarSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputTrocarSenhaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume();
            alterarSenha();
        }
    }//GEN-LAST:event_inputTrocarSenhaKeyPressed

    private void trocarSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_trocarSenhaKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume();
            alterarSenha();
        }
    }//GEN-LAST:event_trocarSenhaKeyPressed

    private void checkMostrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMostrarSenhaActionPerformed
          if(checkMostrarSenha.isSelected())
            inputTrocarSenha.setEchoChar((char) 0);
        else
            inputTrocarSenha.setEchoChar('*');
    }//GEN-LAST:event_checkMostrarSenhaActionPerformed

    private void FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarActionPerformed
        voltarParaLogin();
    }//GEN-LAST:event_FinalizarActionPerformed

    private void FinalizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FinalizarKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            evt.consume();
            voltarParaLogin();
        }
    }//GEN-LAST:event_FinalizarKeyPressed

    private void alterarSenha() {
        if (u == null || u.getId() <= 0) {
            JOptionPane.showMessageDialog(this, "Usuário inválido para alteração de senha.");
            return;
        }

        char[] novaSenha = inputTrocarSenha.getPassword();
        try {
            if (novaSenha.length < 4) {
                JOptionPane.showMessageDialog(this, "A nova senha deve ter pelo menos 4 caracteres.");
                inputTrocarSenha.requestFocusInWindow();
                return;
            }

            String senhaHash = new Criptografia().criptografar(novaSenha);
            if (senhaHash == null) {
                throw new Exception("Não foi possível processar a nova senha.");
            }

            u.setSenhaHash(senhaHash);
            userChangeHashPass.ChangeUserPassword(u);
            u.setDeveTrocarSenha(false);
            inputTrocarSenha.setText("");

            JOptionPane.showMessageDialog(this, "Senha alterada com sucesso.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao alterar senha: " + ex.getMessage());
        } finally {
            Arrays.fill(novaSenha, '\0');
        }
    }

    private void voltarParaLogin() {
        if (u == null || Boolean.TRUE.equals(u.getDeveTrocarSenha())) {
            JOptionPane.showMessageDialog(this, "Altere a senha antes de finalizar.");
            return;
        }

        new TelaLogin().setVisible(true);
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TrocarSenha(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Finalizar;
    private javax.swing.JCheckBox checkMostrarSenha;
    private javax.swing.JPasswordField inputTrocarSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton trocarSenha;
    // End of variables declaration//GEN-END:variables
}
