/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.hospital;

/**
 *
 * @author dpaiv
 */
public class Cadastro extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadastro.class.getName());

    /**
     * Creates new form Cadastro
     */
    public Cadastro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textCadastro = new javax.swing.JLabel();
        textTipoUsuarioCadastro = new javax.swing.JLabel();
        txtCpfCadastro = new javax.swing.JLabel();
        cpfCadastroUsu = new javax.swing.JTextField();
        tipoUsuarioCadastroUsu = new javax.swing.JComboBox<>();
        textNomeCadastro = new javax.swing.JLabel();
        nomeCadastroUsu = new javax.swing.JTextField();
        textSobreNomeCadastro = new javax.swing.JLabel();
        telefoneCadastroUsu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        textSobreNomeCadastro1 = new javax.swing.JLabel();
        emailCadastroUsu = new javax.swing.JTextField();
        textSobreNomeCadastro2 = new javax.swing.JLabel();
        textSobreNomeCadastro3 = new javax.swing.JLabel();
        crmCadastroUsu = new javax.swing.JTextField();
        corenCadastroUsu = new javax.swing.JTextField();
        textSobreNomeCadastro4 = new javax.swing.JLabel();
        especialidadeCadastroUsu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO");

        textCadastro.setFont(new java.awt.Font("Rockwell Condensed", 0, 36)); // NOI18N
        textCadastro.setText("CADASTRO");

        textTipoUsuarioCadastro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textTipoUsuarioCadastro.setText("Tipo de usuário");

        txtCpfCadastro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtCpfCadastro.setText("CPF");

        cpfCadastroUsu.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        cpfCadastroUsu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpfCadastroUsu.setText("Sem Pontos");

        tipoUsuarioCadastroUsu.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        tipoUsuarioCadastroUsu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medico", "Enfermeiro" }));

        textNomeCadastro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textNomeCadastro.setText("Nome:");

        nomeCadastroUsu.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        nomeCadastroUsu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomeCadastroUsu.addActionListener(this::nomeCadastroUsuActionPerformed);

        textSobreNomeCadastro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro.setText("Telefone");

        telefoneCadastroUsu.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Cadastrar");

        textSobreNomeCadastro1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro1.setText("Email");

        emailCadastroUsu.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N

        textSobreNomeCadastro2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro2.setText("CRM");

        textSobreNomeCadastro3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro3.setText("Coren");

        crmCadastroUsu.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        crmCadastroUsu.setText("APENAS PARA MÉDICOS");

        corenCadastroUsu.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        corenCadastroUsu.setText("APENAS PARA ENFERMEIROS");

        textSobreNomeCadastro4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textSobreNomeCadastro4.setText("Especialidade");

        especialidadeCadastroUsu.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        especialidadeCadastroUsu.setText("APENAS PARA MÉDICOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textSobreNomeCadastro4)
                        .addGap(18, 18, 18)
                        .addComponent(especialidadeCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textSobreNomeCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(telefoneCadastroUsu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textNomeCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(nomeCadastroUsu))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCpfCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(cpfCadastroUsu))
                            .addComponent(textCadastro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textTipoUsuarioCadastro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipoUsuarioCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textSobreNomeCadastro1)
                                .addGap(18, 18, 18)
                                .addComponent(emailCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textSobreNomeCadastro2)
                                .addGap(18, 18, 18)
                                .addComponent(crmCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textSobreNomeCadastro3)
                                .addGap(18, 18, 18)
                                .addComponent(corenCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(textCadastro)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTipoUsuarioCadastro)
                    .addComponent(tipoUsuarioCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfCadastro)
                    .addComponent(cpfCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNomeCadastro)
                    .addComponent(nomeCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSobreNomeCadastro)
                    .addComponent(telefoneCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSobreNomeCadastro1)
                    .addComponent(emailCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSobreNomeCadastro4)
                    .addComponent(especialidadeCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSobreNomeCadastro2)
                    .addComponent(crmCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textSobreNomeCadastro3)
                            .addComponent(corenCadastroUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        setSize(new java.awt.Dimension(916, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeCadastroUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeCadastroUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCadastroUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Cadastro dialog = new Cadastro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField corenCadastroUsu;
    private javax.swing.JTextField cpfCadastroUsu;
    private javax.swing.JTextField crmCadastroUsu;
    private javax.swing.JTextField emailCadastroUsu;
    private javax.swing.JTextField especialidadeCadastroUsu;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField nomeCadastroUsu;
    private javax.swing.JTextField telefoneCadastroUsu;
    private javax.swing.JLabel textCadastro;
    private javax.swing.JLabel textNomeCadastro;
    private javax.swing.JLabel textSobreNomeCadastro;
    private javax.swing.JLabel textSobreNomeCadastro1;
    private javax.swing.JLabel textSobreNomeCadastro2;
    private javax.swing.JLabel textSobreNomeCadastro3;
    private javax.swing.JLabel textSobreNomeCadastro4;
    private javax.swing.JLabel textTipoUsuarioCadastro;
    private javax.swing.JComboBox<String> tipoUsuarioCadastroUsu;
    private javax.swing.JLabel txtCpfCadastro;
    // End of variables declaration//GEN-END:variables
}
